In [1]:
# import packages
import numpy as np
import pandas as pd

In [2]:
%pwd

'C:\\Users\\javad\\Desktop\\github\\data-science-portfolio'

In [3]:
df = pd.read_csv(
    './data/stack-overflow-developer-survey-2012/2012 Stack Overflow Survey Results.csv',
    encoding='ISO-8859-2',
    # skiprows=,
    header=[0,1],
    )
df[('ID', 'ID')] = range(1, len(df) + 1)

In [4]:
# Rename columns and determine columns which correspond to
# Mulit-choice questions
columns = []
multichoice_columns = set()

# multi choice answers in stackoverflow 2011 datasets are available
# in different columns such that the first choice has both first 
# header and second header, other choices has only second header
# and when the data is read by pandas their first header will be
# name by convention: Unnamed:
# we will replace the first header of these unnamed with the first
# header of first choice for the question
# questions are in first header and answer choices are in second
# header
for col in list(df.columns):
    multichoice_index = 0
    if col[0].startswith('Unnamed: '):
        columns.append((columns[-1][0], col[1]))
        multichoice_columns.add(columns[-1][0])
    else:
        columns.append((col[0], col[1]))

df.columns = columns

In [5]:
def merge_columns(
    df: pd.core.frame.DataFrame,
    cols_to_merge: list,
    new_col_name: tuple,
    sep: str = '|',
    drop_cols: bool = True,
    ):
    assert type(df) == pd.core.frame.DataFrame
    assert type(cols_to_merge) == list
    assert type(new_col_name) == tuple
    assert type(sep) == str

    df[new_col_name] = ''
    for col in cols_to_merge:
        df[new_col_name] = df[new_col_name].apply(lambda x: x.replace(f"{sep}{sep}", f"{sep}"))
        df[new_col_name] = df[new_col_name].fillna('') + sep +  df[col].fillna('')

    df[new_col_name] = df[new_col_name].apply(lambda x: x.replace(f"{sep}{sep}", f"{sep}"))
    df[new_col_name] = df[new_col_name].apply(lambda x: x[1:] if x.startswith(sep) else x)
    df[new_col_name] = df[new_col_name].apply(lambda x: x[:-1] if x.endswith(sep) else x)
    if drop_cols:
        df.drop(cols_to_merge, inplace=True, axis=1)

    return df


for field in multichoice_columns:
    cols_to_merge = list(filter(lambda x: x[0] == field, list(df.columns)))
    if len(cols_to_merge) > 1:
        df = merge_columns(
            df,
            cols_to_merge=cols_to_merge,
            new_col_name=(field, 'Multi-choice'),
            sep='|'
        )


df.columns

Index([                                                                                      ('What Country or Region do you live in?', 'Response'),
                                                                                        ('Which US State or Territory do you live in?', 'Response'),
                                                                                                                   ('How old are you?', 'Response'),
                                                                           ('How many years of IT/Programming experience do you have?', 'Response'),
                                                                    ('How would you best describe the industry you currently work in?', 'Response'),
                                                                                     ('Which best describes the size of your company?', 'Response'),
                                                                             ('Which of the following best describes your occupation?', 'Response'),
                                       ('What is your budget for outside expenditures (hardware, software, consulting, etc) for 2011?', 'Response'),
                                                                                           ('What type of project are you developing?', 'Response'),
                                                                                ('Which desktop operating system do you use the most?', 'Response'),
                                                                               ('What best describes your career / job satisfaction? ', 'Response'),
                                                                          ('Including bonus, what is your annual compensation in USD?', 'Response'),
                                                                        ('Have you visited / Are you aware of Stack Overflow Careers?', 'Response'),
                                                                                      ('Do you have a Stack Overflow Careers Profile?', 'Response'),
                                    ('In the last 12 months, how much money have you spent on personal technology-related purchases? ', 'Response'),
                                                              ('What advertisers do you remember seeing on Stack Overflow?', 'Open-Ended Response'),
                                                                                    ('What is your current Stack Overflow reputation?', 'Response'),
                                                                                                                                       ('ID', 'ID'),
                                                          ('You answered you don't have a Careers profile, can you elaborate why?', 'Multi-choice'),
                                                                                       ('Which of our sites do you frequent most?', 'Multi-choice'),
                                                                      ('Please rate the advertising you've seen on Stack Overflow', 'Multi-choice'),
                                                                                   ('What types of purchases are you involved in?', 'Multi-choice'),
       ('What is your involvement in purchasing products or services for the company you work for? (You can choose more than one)', 'Multi-choice'),
                                                           ('Which technology products do you own? (You can choose more than one)', 'Multi-choice'),
                                                                                         ('Which languages are you proficient in?', 'Multi-choice')],
      dtype='object')

In [6]:
len(df)

6243

In [7]:
def split_row_to_rows_1NF(data: dict):
    """Creates several rows from given row to obtain 1NF.
    """
    n1_data = []
    for (header_0, header_1), value in data.items():
        if header_1 == 'Response':
            if n1_data == []:
                n1_data.append({(header_0, '1NF'): value})
            else:
                for item in n1_data:
                    item[(header_0, '1NF')] = value

        if header_1 == 'ID':
            if n1_data == []:
                n1_data.append({(header_0, '1NF'): value})
            else:
                for item in n1_data:
                    item[(header_0, '1NF')] = value

        if header_1 == 'Multi-choice':
            selections = data[(header_0, header_1)].split("|")
            if n1_data == []:
                for selection in selections:
                    n1_data.append({(header_0, '1NF'): value})
            else:
                if selections:
                    new_list = []
                    for item in n1_data:
                        for selection in selections:
                            item_copy = item.copy()
                            item_copy[(header_0, '1NF')] = selection
                            new_list.append(item_copy)
                    n1_data = new_list

    return n1_data


def split_df_columns_to_2NF(
    df_1NF: pd.core.frame.DataFrame,
    columns_to_separate: list,
    id_column=('ID', '1NF')
    ):
    join_df = df_1NF[[id_column] + columns_to_separate].copy().drop_duplicates()
    new_df = join_df.drop(id_column, axis=1).drop_duplicates()
    df_non_duplicate = df_1NF.drop(columns_to_separate, axis=1).drop_duplicates()
    return df_non_duplicate, join_df, new_df


def df_to_2NF(
    df_1NF,
):
    join_dfs = {}
    new_dfs = {}
    for choice in multichoice_columns:
        df_1NF, join_df, new_df = split_df_columns_to_2NF(
            df_1NF,
            [(choice, '1NF')],
        )
        join_dfs[choice] = join_df
        new_dfs[choice] = join_df
        
    return df_1NF, join_dfs, new_dfs
        



def df_to_1NF(df):
    """Creates 1NF dataframe from given dataframe.
    """
    data_list = df.to_dict(orient='recrods')
    new_data_list = []
    for row in data_list:
        new_data_list += split_row_to_rows_1NF(row)
    return pd.DataFrame(new_data_list)


df_1NF = df_to_1NF(df)
df_2NF, join_dfs, new_dfs = df_to_2NF(df_1NF)

C:\Users\javad\AppData\Local\Temp\ipykernel_6412\701762451.py:70: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  data_list = df.to_dict(orient='recrods')

In [9]:
df_2NF

,"(What Country or Region do you live in?, 1NF)","(Which US State or Territory do you live in?, 1NF)","(How old are you?, 1NF)","(How many years of IT/Programming experience do you have?, 1NF)","(How would you best describe the industry you currently work in?, 1NF)","(Which best describes the size of your company?, 1NF)","(Which of the following best describes your occupation?, 1NF)","(What is your budget for outside expenditures (hardware, software, consulting, etc) for 2011?, 1NF)","(What type of project are you developing?, 1NF)","(Which desktop operating system do you use the most?, 1NF)","(What best describes your career / job satisfaction? , 1NF)","(Including bonus, what is your annual compensation in USD?, 1NF)","(Have you visited / Are you aware of Stack Overflow Careers?, 1NF)","(Do you have a Stack Overflow Careers Profile?, 1NF)","(In the last 12 months, how much money have you spent on personal technology-related purchases? , 1NF)","(What is your current Stack Overflow reputation?, 1NF)","(ID, 1NF)"
0,India,NaN,20-24,<2,Consulting,"Fortune 1000 (1,000+)",Server Programmer,"<$10,000",SaaS,Linux,Love my job,"<$20,000",Yes,"No, but I want one! (Please provide email and ...","$501-$1,000",NaN,1
150,Germany,NaN,25-29,<2,Other,Mature Small Business (25-100),Embedded Application Developer,Don't know,Mobile,Windows 7,I enjoy going to work,"$20,000 - $40,000",No,No thank you,$100-$250,Don't have an account,2
222,United Kingdom,NaN,20-24,41070,Finance / Banking,Mature Small Business (25-100),Web Application Developer,"$25,001 - $40,000",Web Platform,Mac OS X,I enjoy going to work,"$20,000 - $40,000",Yes,No thank you,"$1,001-$2,000",1,3
1422,France,NaN,20-24,40944,Software Products,Mature Small Business (25-100),Embedded Application Developer,NaN,Mobile,Linux,I'm not happy in my job,"$20,000 - $40,000",Yes,"No, but I want one! (Please provide email and ...","$1,001-$2,000",Don't have an account,4
1446,United States of America,Iowa,< 20,40944,Other,Student,Student,NaN,Mobile,Mac OS X,I wish I had a job!,Student / Unemployed,No,No thank you,$251-$500,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3029041,Russia,NaN,20-24,40944,Software Products,Student,Embedded Application Developer,"<$10,000",Mobile,Windows 7,Love my job,Student / Unemployed,Yes,No thank you,"$1,001-$2,000",3000,6239
3029113,Africa,NaN,20-24,<2,Consulting,Mid Sized (100-999),Web Application Developer,NaN,Mobile,Linux,Hate my job,NaN,NaN,NaN,NaN,10000,6240
3029116,United States of America,Iowa,20-24,40944,Finance / Banking,"Fortune 1000 (1,000+)",Server Programmer,NaN,Enterprise,Windows 7,Its a paycheck,"$40,000 - $60,000",Yes,"No, but I want one! (Please provide email and ...","$1,001-$2,000",1000,6241
3029134,Other Europe,NaN,40-50,11,Foundation / Non-Profit,Mid Sized (100-999),Manager of Developers or Team Leader,"$41,000 - $75,000",Other,Linux,Love my job,"$80,000 - $100,000",Yes,No thank you,"$1,001-$2,000",1000,6242
3029374,United States of America,Texas,30-34,41070,Software Products,Mature Small Business (25-100),Desktop Application Developer,Don't know,Other,Windows 7,Love my job,"$80,000 - $100,000",Yes,"No, but I want one! (Please provide email and ...",$251-$500,NaN,6243

In [8]:
df_2NF.columns

Index([                                                         ('What Country or Region do you live in?', '1NF'),
                                                           ('Which US State or Territory do you live in?', '1NF'),
                                                                                      ('How old are you?', '1NF'),
                                              ('How many years of IT/Programming experience do you have?', '1NF'),
                                       ('How would you best describe the industry you currently work in?', '1NF'),
                                                        ('Which best describes the size of your company?', '1NF'),
                                                ('Which of the following best describes your occupation?', '1NF'),
          ('What is your budget for outside expenditures (hardware, software, consulting, etc) for 2011?', '1NF'),
                                                              ('What type of project are you developing?', '1NF'),
                                                   ('Which desktop operating system do you use the most?', '1NF'),
                                                  ('What best describes your career / job satisfaction? ', '1NF'),
                                             ('Including bonus, what is your annual compensation in USD?', '1NF'),
                                           ('Have you visited / Are you aware of Stack Overflow Careers?', '1NF'),
                                                         ('Do you have a Stack Overflow Careers Profile?', '1NF'),
       ('In the last 12 months, how much money have you spent on personal technology-related purchases? ', '1NF'),
                                                       ('What is your current Stack Overflow reputation?', '1NF'),
                                                                                                    ('ID', '1NF')],
      dtype='object')

In [34]:
columns = [
    'country',
    'state_US',
    'age',
    'years_of_experience',
    'industry',
    'company_size',
    'occupation',
    'act_upon_recommendation',
    'involvement_in_purchase',
]
df.columns = columns + list(df.columns)[len(columns):]
list(df.columns)

['country',
 'state_US',
 'age',
 'years_of_experience',
 'industry',
 'company_size',
 'occupation',
 'act_upon_recommendation',
 'involvement_in_purchase',
 ('What operating system do you use the most?', 'Response'),
 ('Please rate your job/career satisfaction', 'Response'),
 ('Including bonus, what is your annual compensation in USD?', 'Response'),
 ('In the last 12 months, how much money have you spent on personal technology-related purchases? ',
  'Response'),
 ('Which of our sites do you frequent most?', 'Response'),
 ('ID', 'ID'),
 ('Which languages are you proficient in?', 'Multi-choice'),
 ('What is your involvement in purchasing? You can choose more than 1.',
  'Multi-choice'),
 ('Which technology products do you own? (You can choose more than one)',
  'Multi-choice'),
 ('What types of purchases are you involved in?', 'Multi-choice'),
 ('What is your budget for outside expenditures (hardware, software, consulting, etc) for 2011?',
  'Multi-choice')]

In [29]:
df.columns

Index([                                                                                                      'country',
                                                                                                            'state_US',
                                                                                                                 'age',
                                                                                                 'years_of_experience',
                                                                                                            'industry',
                                                                                                        'company_size',
                                                                                                          'occupation',
                                                                                             'act_upon_recommendation',
                                                                                             'involvement_in_purchase',
                                                                                 ('Unnamed: 9_level_0', 'Recommender'),
                                                                                   ('Unnamed: 10_level_0', 'Approver'),
                                                                                  ('Unnamed: 11_level_0', 'Purchaser'),
                                                                               ('Unnamed: 12_level_0', 'Check Writer'),
                                                                             ('Unnamed: 13_level_0', 'No Involvement'),
                                                                               ('Unnamed: 14_level_0', 'I'm a Seller'),
                                                          ('What types of purchases are you involved in?', 'Hardware'),
                                                                                    ('Unnamed: 16_level_0', 'Servers'),
                                                                                   ('Unnamed: 17_level_0', 'Software'),
                                                     ('Unnamed: 18_level_0', 'User Equipment: Monitors, PCs, Laptops'),
                                                                                ('Unnamed: 19_level_0', 'Consultants'),
                                                                                      ('Unnamed: 20_level_0', 'Other'),
          ('What is your budget for outside expenditures (hardware, software, consulting, etc) for 2011?', '<$10,000'),
                                                                          ('Unnamed: 22_level_0', '$10,001 - $25,000'),
                                                                          ('Unnamed: 23_level_0', '$25,001 - $40,000'),
                                                                          ('Unnamed: 24_level_0', '$41,000 - $75,000'),
                                                                         ('Unnamed: 25_level_0', '$75,001 - $100,000'),
                                                                        ('Unnamed: 26_level_0', '$100,001 - $150,000'),
                                                                                  ('Unnamed: 27_level_0', '>$150,000'),
                                                                                 ('Unnamed: 28_level_0', 'Don't know'),
                                                              ('What type of project are you developing?', 'Response'),
                                                                    ('Which languages are you proficient in?', 'Java'),
                                                                                 ('Unnamed: 31_level_0', 'JavaScript'),
                                                                                        ('Unnamed: 32_level_0', 'CSS'),
                                                                                        ('Unnamed: 33_level_0', 'PHP'),
                                                                                     ('Unnamed: 34_level_0', 'Python'),
                                                                                       ('Unnamed: 35_level_0', 'Ruby'),
                                                                                        ('Unnamed: 36_level_0', 'SQL'),
                                                                                         ('Unnamed: 37_level_0', 'C#'),
                                                                                        ('Unnamed: 38_level_0', 'C++'),
                                                                                          ('Unnamed: 39_level_0', 'C'),
                                                                                       ('Unnamed: 40_level_0', 'Perl'),
                                                                                       ('Unnamed: 41_level_0', 'None'),
                                                                     ('Unnamed: 42_level_0', 'other (please specify)'),
                                                            ('What operating system do you use the most?', 'Response'),
                                                              ('Please rate your job/career satisfaction', 'Response'),
                                             ('Including bonus, what is your annual compensation in USD?', 'Response'),
                                    ('Which technology products do you own? (You can choose more than one)', 'iPhone'),
                                                                                    ('Unnamed: 47_level_0', 'Android'),
                                                                                 ('Unnamed: 48_level_0', 'Blackberry'),
                                                                          ('Unnamed: 49_level_0', 'Other Smart Phone'),
                                                                       ('Unnamed: 50_level_0', 'Regular Mobile Phone'),
                                                                                     ('Unnamed: 51_level_0', 'Kindle'),
                                                                                       ('Unnamed: 52_level_0', 'Nook'),
                                                                                    ('Unnamed: 53_level_0', 'Blu-Ray'),
                                                                                       ('Unnamed: 54_level_0', 'HDTV'),
                                                                                    ('Unnamed: 55_level_0', 'AppleTV'),
                                                                                       ('Unnamed: 56_level_0', 'iPad'),
                                                                              ('Unnamed: 57_level_0', 'Other netbook'),
                                                                                        ('Unnamed: 58_level_0', 'PS3'),
                                                                                       ('Unnamed: 59_level_0', 'Xbox'),
                                                                                        ('Unnamed: 60_level_0', 'Wii'),
                                                                        ('Unnamed: 61_level_0', 'Other gaming system'),
                                                                     ('Unnamed: 62_level_0', 'other (please specify)'),
       ('In the last 12 months, how much money have you spent on personal technology-related purchases? ', 'Response'),
                                                              ('Which of our sites do you frequent most?', 'Response')],
      dtype='object')